version: '3'

volumes:
  database_parsing:

networks:
  databaseparsing-network:

services:
  database_parsing:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: database_parsing
    container_name: database_parsing
    restart: unless-stopped
    hostname: localhost
    ports:
      - 8080:8080
    networks:
      - databaseparsing-network

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - 5432:5432
    networks:
      - databaseparsing-network
